
 Executando: C:\Users\Danilo\Downloads\dossel_project\venv\scripts\python.exe Scripts\Mapeador_Completo.py documento_teste_erros (1)_rN5pEAA.docx --id_revisao 34
 Cancelamento detectado para a revisão 34.
 Cancelamento solicitado; encerrando subprocesso …
--- GERENCIADOR INICIADO COM SUCESSO ---
 Arquivo 'documento_teste_erros (1)_rN5pEAA.docx' copiado para a pasta 'C:\Users\Danilo\Downloads\dossel_project\media\entrada'.

 Documento a processar: ['documento_teste_erros (1)_rN5pEAA.docx']
 Modo de revisão: completa
 E-mail destino: n.danilo@dosselambiental.com.br
 Progresso atualizado para: 5% (ID da Revisão: 34)

 Iniciando processamento paralelo de 'Scripts\Mapeador_Completo.py' para 1 documento(s).
 Houve falhas durante o processamento paralelo de 'Scripts\Mapeador_Completo.py'.
 Falhas durante o processamento. O processo pode ter sido cancelado.
 Progresso atualizado para: 100% (ID da Revisão: 34)
 Gerenciador finalizou a execução.
